server:
  port: 8082
spring:
  application:
    name: Calendar-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultZone: http://localhost:8761/eureka