server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    jpa:
      hibernate:
        ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true


eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka